name            = Common Plugin for Doma Repository
description     = A common plugin for repository management using doma.
version         = 1.0.0

url             = https://github.com/Akazukin-Team/Java-Common-Plugin-Repo-Doma

vendor          = Akazukin Team
vendor-url      = https://github.com/Akazukin-Team

groupId         = org.akazukin.plugin
artifactId      = common-repo-doma

archiveBaseName = Common-Repo-Doma
